services:
  app:
    build: .
    ports:
      - "8080:8080"
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USER: user
      DB_PASSWORD: password
      DB_NAME: mydb
      DB_SSLMODE: disable
    depends_on:
      - postgres

  postgres:
    image: postgres:13-alpine
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./pkg/db/schema.sql:/docker-entrypoint-initdb.d/schema.sql

volumes:
  postgres_data:
